//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2019.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2019.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ##.###.#.......#.#....#....#..........#.
        ///....#..#..#.....#.##.............#......
        ///...#.#..###..#..#.....#........#......#.
        ///#......#.....#.##.#.##.##...#...#......#
        ///.............#....#.....#.#......#.#....
        ///..##.....#..#..#.#.#....##.......#.....#
        ///.#........#...#...#.#.....#.....#.#..#.#
        ///...#...........#....#..#.#..#...##.#.#..
        ///#.##.#.#...#..#...........#..........#..
        ///........#.#..#..##.#.##......##.........
        ///................#.##.#....##.......#....
        ///#............#.........###...#...#.....#
        ///#....#.. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3,8,1005,8,318,1106,0,11,0,0,0,104,1,104,0,3,8,102,-1,8,10,1001,10,1,10,4,10,1008,8,1,10,4,10,101,0,8,29,1,107,12,10,2,1003,8,10,3,8,102,-1,8,10,1001,10,1,10,4,10,1008,8,0,10,4,10,1002,8,1,59,1,108,18,10,2,6,7,10,2,1006,3,10,3,8,1002,8,-1,10,1001,10,1,10,4,10,1008,8,1,10,4,10,1002,8,1,93,1,1102,11,10,3,8,102,-1,8,10,1001,10,1,10,4,10,108,1,8,10,4,10,101,0,8,118,2,1102,10,10,3,8,102,-1,8,10,101,1,10,10,4,10,1008,8,0,10,4,10,101,0,8,145,1006,0,17,1006,0,67,3,8,1002,8,-1,10,101,1,10,10,4,10,1008,8,0,10,4,10,10 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;x=5, y=13, z=-3&gt;
        ///&lt;x=18, y=-7, z=13&gt;
        ///&lt;x=16, y=3, z=4&gt;
        ///&lt;x=0, y=8, z=8&gt;.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1,380,379,385,1008,2563,464403,381,1005,381,12,99,109,2564,1102,1,0,383,1101,0,0,382,20101,0,382,1,20102,1,383,2,21102,37,1,0,1106,0,578,4,382,4,383,204,1,1001,382,1,382,1007,382,37,381,1005,381,22,1001,383,1,383,1007,383,26,381,1005,381,18,1006,385,69,99,104,-1,104,0,4,386,3,384,1007,384,0,381,1005,381,94,107,0,384,381,1005,381,108,1105,1,161,107,1,392,381,1006,381,161,1101,0,-1,384,1106,0,119,1007,392,35,381,1006,381,161,1102,1,1,384,20101,0,392,1,21102,1,24,2,21102,0,1,3,21102,138,1,0,1105,1,549,1,392,38 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 PTZH, 14 MHDKS, 9 MPBVZ =&gt; 4 BDRP
        ///4 VHPGT, 12 JSPDJ, 1 WNSC =&gt; 2 XCTCF
        ///174 ORE =&gt; 4 JVNH
        ///7 JVNH =&gt; 4 BTZH
        ///12 XLNZ, 1 CZLDF =&gt; 8 NDHSR
        ///1 VDVQ, 1 PTZH =&gt; 7 LXVZ
        ///1 ZDQRT =&gt; 5 KJCJL
        ///2 SGDXK, 6 VDVQ, 1 RLFHL =&gt; 7 GFNQ
        ///8 JFBD =&gt; 5 VDVQ
        ///1 SGDXK =&gt; 6 ZNBSR
        ///2 PNZD, 1 JFBD =&gt; 7 TVRMW
        ///11 TRXG, 4 CVHR, 1 VKXL, 63 GFNQ, 1 MGNW, 59 PFKHV, 22 KFPT, 3 KFCJC =&gt; 1 FUEL
        ///6 BTZH =&gt; 8 GTWKH
        ///5 WHVKJ, 1 QMZJX =&gt; 6 XLNZ
        ///18 JSPDJ, 11 QMZJX =&gt; 5 RWQC
        ///2 WFHXK =&gt; 4 JSPDJ
        ///2 GHZW =&gt; 3 RLFHL
        ///4 WHVKJ, 2 RWQC, 2 PTZH =&gt; 8 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3,1033,1008,1033,1,1032,1005,1032,31,1008,1033,2,1032,1005,1032,58,1008,1033,3,1032,1005,1032,81,1008,1033,4,1032,1005,1032,104,99,1002,1034,1,1039,102,1,1036,1041,1001,1035,-1,1040,1008,1038,0,1043,102,-1,1043,1032,1,1037,1032,1042,1106,0,124,1002,1034,1,1039,1001,1036,0,1041,1001,1035,1,1040,1008,1038,0,1043,1,1037,1038,1042,1105,1,124,1001,1034,-1,1039,1008,1036,0,1041,1001,1035,0,1040,1002,1038,1,1043,101,0,1037,1042,1105,1,124,1001,1034,1,1039,1008,1036,0,1041,102,1,1035,1040,1001,1038,0,1043,101,0,103 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day15Input {
            get {
                return ResourceManager.GetString("Day15Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 59769638638635227792873839600619296161830243411826562620803755357641409702942441381982799297881659288888243793321154293102743325904757198668820213885307612900972273311499185929901117664387559657706110034992786489002400852438961738219627639830515185618184324995881914532256988843436511730932141380017180796681870256240757580454505096230610520430997536145341074585637105456401238209187118397046373589766408080120984817035699228422366952628344235542849850709181363703172334788744537357607446322903743644673800140770 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1,330,331,332,109,3546,1101,1182,0,15,1101,1439,0,24,1002,0,1,570,1006,570,36,1001,571,0,0,1001,570,-1,570,1001,24,1,24,1106,0,18,1008,571,0,571,1001,15,1,15,1008,15,1439,570,1006,570,14,21101,0,58,0,1105,1,786,1006,332,62,99,21102,1,333,1,21102,73,1,0,1106,0,579,1101,0,0,572,1101,0,0,573,3,574,101,1,573,573,1007,574,65,570,1005,570,151,107,67,574,570,1005,570,151,1001,574,-64,574,1002,574,-1,574,1001,572,1,572,1007,572,11,570,1006,570,165,101,1182,572,127,1001,574,0,0,3,574,101,1,573,573,1008,574,10,570,10 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day17Input {
            get {
                return ResourceManager.GetString("Day17Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #################################################################################
        ///#...........#.......................#...#.........#.....#.....#...Q.............#
        ///###.#######.#################.#.###.###G#.#####.#.#.#.###.#.#.#.#######.#####.###
        ///#...#.......................#.#.#.......#...#...#z#.#...#.#.#.#...#u..#....b#...#
        ///#.#########################.###.#######.###.#.#####.###.#.#.#####.#.#.#####.###.#
        ///#.............#...#l....#.#...#.....#.#.#...#...#...#...#.#.....#.#.#...#...#...#
        ///#.###########. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day18Input {
            get {
                return ResourceManager.GetString("Day18Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 109,424,203,1,21101,0,11,0,1106,0,282,21102,18,1,0,1105,1,259,1202,1,1,221,203,1,21102,31,1,0,1106,0,282,21101,0,38,0,1106,0,259,20101,0,23,2,21201,1,0,3,21101,0,1,1,21101,57,0,0,1105,1,303,1202,1,1,222,21001,221,0,3,21001,221,0,2,21101,0,259,1,21101,80,0,0,1105,1,225,21101,119,0,2,21102,1,91,0,1106,0,303,2101,0,1,223,20102,1,222,4,21102,1,259,3,21101,0,225,2,21101,0,225,1,21101,0,118,0,1105,1,225,21002,222,1,3,21101,97,0,2,21101,133,0,0,1106,0,303,21202,1,-1,1,22001,223,1,1,21102,148,1,0,1105,1,259,1201,1, [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day19Input {
            get {
                return ResourceManager.GetString("Day19Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 94164
        ///100562
        ///114499
        ///134308
        ///138764
        ///114494
        ///70457
        ///113793
        ///117753
        ///77795
        ///110371
        ///113357
        ///118839
        ///99757
        ///119918
        ///145232
        ///147113
        ///142411
        ///93053
        ///81783
        ///124022
        ///98470
        ///77368
        ///75163
        ///79175
        ///131174
        ///93196
        ///121875
        ///86016
        ///148758
        ///126577
        ///109812
        ///105696
        ///66318
        ///146939
        ///113236
        ///130014
        ///135719
        ///127114
        ///69700
        ///109416
        ///64168
        ///89215
        ///69015
        ///128511
        ///59682
        ///79067
        ///58795
        ///145447
        ///129419
        ///93058
        ///63860
        ///146148
        ///58364
        ///74149
        ///81871
        ///116469
        ///131739
        ///132852
        ///148040
        ///98865
        ///56588
        ///79326
        ///114713
        ///52397
        ///134887
        ///114809
        ///11335 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I     U       O   M           N     O       S                                         
        ///                                           X     T       X   C           D     N       A                                         
        ///  #########################################.#####.#######.###.###########.#####.#######.#######################################  
        ///  #.....#.......#.....#.....#.....#...#.#...#...#...#.....#.#...........#.....#.....#.............#.#...#...#...#.......#.....#  
        ///  #####.#######.#####.#####.#.# [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day20Input {
            get {
                return ResourceManager.GetString("Day20Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 109,2050,21102,966,1,1,21101,0,13,0,1106,0,1378,21101,0,20,0,1106,0,1337,21101,0,27,0,1106,0,1279,1208,1,65,748,1005,748,73,1208,1,79,748,1005,748,110,1208,1,78,748,1005,748,132,1208,1,87,748,1005,748,169,1208,1,82,748,1005,748,239,21101,0,1041,1,21101,73,0,0,1105,1,1421,21101,0,78,1,21101,1041,0,2,21102,88,1,0,1105,1,1301,21101,0,68,1,21101,0,1041,2,21102,1,103,0,1105,1,1301,1101,0,1,750,1105,1,298,21102,1,82,1,21102,1041,1,2,21101,0,125,0,1106,0,1301,1101,2,0,750,1105,1,298,21102,1,79,1,21101,1041,0,2,211 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day21Input {
            get {
                return ResourceManager.GetString("Day21Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deal with increment 73
        ///cut -6744
        ///deal into new stack
        ///cut 9675
        ///deal with increment 63
        ///cut -8047
        ///deal with increment 21
        ///cut -4726
        ///deal with increment 39
        ///cut -537
        ///deal with increment 39
        ///cut -6921
        ///deal with increment 15
        ///cut 2673
        ///deal into new stack
        ///cut 2483
        ///deal with increment 66
        ///deal into new stack
        ///cut 1028
        ///deal with increment 48
        ///deal into new stack
        ///cut -418
        ///deal with increment 15
        ///cut 9192
        ///deal with increment 62
        ///deal into new stack
        ///deal with increment 23
        ///cut 2840
        ///deal with increment [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day22Input {
            get {
                return ResourceManager.GetString("Day22Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3,62,1001,62,11,10,109,2233,105,1,0,889,2099,1631,2130,668,994,1693,825,1819,1753,1600,1402,1023,1334,2161,1984,854,571,1786,734,1912,2198,1132,1538,1464,1569,1369,796,639,1101,1722,1062,2015,765,2058,1503,930,965,1850,1274,1202,1883,1303,1163,1662,1949,602,697,1237,1433,0,0,0,0,0,0,0,0,0,0,0,0,3,64,1008,64,-1,62,1006,62,88,1006,61,170,1106,0,73,3,65,20101,0,64,1,21001,66,0,2,21102,1,105,0,1105,1,436,1201,1,-1,64,1007,64,0,62,1005,62,73,7,64,67,62,1006,62,73,1002,64,2,132,1,132,68,132,1001,0,0,62,1001,132,1 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day23Input {
            get {
                return ResourceManager.GetString("Day23Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ##.##
        ///.#.##
        ///##..#
        ///#.#..
        ///.###..
        /// </summary>
        internal static string Day24Input {
            get {
                return ResourceManager.GetString("Day24Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 109,4792,21101,0,3124,1,21102,13,1,0,1106,0,1424,21102,1,166,1,21101,24,0,0,1106,0,1234,21101,0,31,0,1105,1,1984,1105,1,13,6,4,3,2,52,51,21,4,28,56,55,3,19,-9,-10,47,89,88,90,90,6,77,73,85,71,1,76,68,63,65,22,-27,70,76,81,87,5,105,105,107,108,95,4,97,92,109,109,5,110,105,110,108,95,4,115,96,109,109,13,-3,59,101,85,92,97,13,84,80,92,78,34,-15,26,-16,46,88,72,79,84,0,72,76,-3,85,74,79,75,-8,64,68,75,57,65,70,64,66,72,8,-41,32,-22,56,77,82,-4,60,76,62,70,-2,74,-11,55,52,68,67,73,56,60,52,-20,44,56,66,-24,48,58 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day25Input {
            get {
                return ResourceManager.GetString("Day25Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1,12,2,3,1,1,2,3,1,3,4,3,1,5,0,3,2,1,6,19,2,19,6,23,1,23,5,27,1,9,27,31,1,31,10,35,2,35,9,39,1,5,39,43,2,43,9,47,1,5,47,51,2,51,13,55,1,55,10,59,1,59,10,63,2,9,63,67,1,67,5,71,2,13,71,75,1,75,10,79,1,79,6,83,2,13,83,87,1,87,6,91,1,6,91,95,1,10,95,99,2,99,6,103,1,103,5,107,2,6,107,111,1,10,111,115,1,115,5,119,2,6,119,123,1,123,5,127,2,127,6,131,1,131,5,135,1,2,135,139,1,139,13,0,99,2,0,14,0.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a R991,U557,R554,U998,L861,D301,L891,U180,L280,D103,R828,D58,R373,D278,L352,D583,L465,D301,R384,D638,L648,D413,L511,U596,L701,U463,L664,U905,L374,D372,L269,U868,R494,U294,R661,U604,L629,U763,R771,U96,R222,U227,L97,D793,L924,U781,L295,D427,R205,D387,L455,D904,R254,D34,R341,U268,L344,D656,L715,U439,R158,U237,R199,U729,L428,D125,R487,D506,R486,D496,R932,D918,R603,U836,R258,U15,L120,U528,L102,D42,R385,U905,L472,D351,R506,U860,L331,D415,R963,D733,R108,D527,L634,U502,L553,D623,R973,U209,L632,D588,R264,U553,L768,D68 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 193651-649729.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3,225,1,225,6,6,1100,1,238,225,104,0,101,14,135,224,101,-69,224,224,4,224,1002,223,8,223,101,3,224,224,1,224,223,223,102,90,169,224,1001,224,-4590,224,4,224,1002,223,8,223,1001,224,1,224,1,224,223,223,1102,90,45,224,1001,224,-4050,224,4,224,102,8,223,223,101,5,224,224,1,224,223,223,1001,144,32,224,101,-72,224,224,4,224,102,8,223,223,101,3,224,224,1,223,224,223,1102,36,93,225,1101,88,52,225,1002,102,38,224,101,-3534,224,224,4,224,102,8,223,223,101,4,224,224,1,223,224,223,1102,15,57,225,1102,55,49,225,1102,11 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FGY)61Z
        ///2BN)LM7
        ///QXY)TVB
        ///5M5)Y6C
        ///2L2)64M
        ///6TT)183
        ///H6P)6TT
        ///LPL)WP5
        ///TDW)SDV
        ///4N3)LHM
        ///MJ7)STL
        ///V17)4QM
        ///2XW)R2P
        ///CMK)P3C
        ///KN5)XBH
        ///4GV)Z17
        ///VQW)KD6
        ///N6Q)GBK
        ///LZC)5R2
        ///3Z1)L7Y
        ///1LV)QCF
        ///NQ5)6K4
        ///3XX)D1H
        ///YT6)DXZ
        ///JFB)CMF
        ///NFC)DYG
        ///VG6)W38
        ///31Z)TCV
        ///597)H8Q
        ///GK1)MSN
        ///69N)W4Y
        ///3NY)1FX
        ///W81)3XX
        ///LP1)KBR
        ///3KD)X65
        ///YSD)HLF
        ///WKN)NXN
        ///C9S)NYS
        ///9DX)Y3V
        ///VY4)YSL
        ///2V4)79M
        ///X68)1RB
        ///53T)H97
        ///TKM)2J1
        ///K8M)N95
        ///HZ2)J3B
        ///R6Z)KQ1
        ///96F)5WS
        ///W68)KQ5
        ///H4G)NCN
        ///WXV)BH6
        ///8Z1)KVB
        ///WGQ)18Y
        ///4M1)9D8
        ///2NH)RLJ
        ///KVB)1Y5
        ///3SG)RFG        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day6Input {
            get {
                return ResourceManager.GetString("Day6Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3,8,1001,8,10,8,105,1,0,0,21,38,55,80,97,118,199,280,361,442,99999,3,9,101,2,9,9,1002,9,5,9,1001,9,4,9,4,9,99,3,9,101,5,9,9,102,2,9,9,1001,9,5,9,4,9,99,3,9,1001,9,4,9,102,5,9,9,101,4,9,9,102,4,9,9,1001,9,4,9,4,9,99,3,9,1001,9,3,9,1002,9,2,9,101,3,9,9,4,9,99,3,9,101,5,9,9,1002,9,2,9,101,3,9,9,1002,9,5,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,101,1,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,101,1,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,101,2,9,9,4,9,3,9,1002,9,2,9,4,9,99,3,9,102,2,9, [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 22222202202222222222202222222212212222221222212222202221222220222222222122212222102222222220202222022222222222202022222200222222222222220022222220222022222222202222222222212222222202202222220222222222212221222220222222220022212222202222222222222222222222222222222222222222222222222222220122222222222202222222202222221222212222202212222222221222212222222221222220222222222022212222122222222222202222222222222222211022222202222222222222222122222222222022222202212222220222222222222202212222221222212222212220222220 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day8Input {
            get {
                return ResourceManager.GetString("Day8Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1102,34463338,34463338,63,1007,63,34463338,63,1005,63,53,1102,3,1,1000,109,988,209,12,9,1000,209,6,209,3,203,0,1008,1000,1,63,1005,63,65,1008,1000,2,63,1005,63,904,1008,1000,0,63,1005,63,58,4,25,104,0,99,4,0,104,0,99,4,17,104,0,99,0,0,1102,1,30,1010,1102,1,38,1008,1102,1,0,1020,1102,22,1,1007,1102,26,1,1015,1102,31,1,1013,1102,1,27,1014,1101,0,23,1012,1101,0,37,1006,1102,735,1,1028,1102,1,24,1009,1102,1,28,1019,1102,20,1,1017,1101,34,0,1001,1101,259,0,1026,1101,0,33,1018,1102,1,901,1024,1101,21,0,1016,1101, [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Day9Input {
            get {
                return ResourceManager.GetString("Day9Input", resourceCulture);
            }
        }
    }
}
